name: Docker Build

on:
  workflow_dispatch:

  push:
    branches: master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Github Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: dl-system
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Tencent Docker Login
        uses: docker/login-action@v1
        with:
          registry: hkccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_USER }}
          password: ${{ secrets.TENCENT_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/dl-system/system:latest
            ghcr.io/dl-system/system:master
            hkccr.ccs.tencentyun.com/dovhk/system:latest
            hkccr.ccs.tencentyun.com/dovhk/system:master
